# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# SEO
permalink: /blog/:title
url: https://deltalocalmarketing.it
baseurl:
title: Delta Local Marketing

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

sass:
    style: compressed

paginate: 6
paginate_path: "/blog/:num"


# Social
facebook: https://www.facebook.com/deltalocalmarketing/ 
instagram: https://www.instagram.com/deltalocalmarketing/
linkedin: https://www.linkedin.com/company/delta-local-marketing/ 
email: info@deltalocalmarketing.it


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
