- title: Branding
  text: Sviluppiamo un identità per il tuo business
  icon: assets/img/100-1.png

- title: Social media marketing
  text: Raggiungere nuovi clienti
  icon: assets/img/100-2.png

- title: Web marketing
  text: Concretizzare traffico qualificato al sito web dell'azienda
  icon: assets/img/100-3.png

- title: Search Engine Optimization
  text: Tecniche di ottimizzazione web per una adeguata indicizzazione del sito da parte dei mototri di ricerca
  icon: assets/img/100-4.png

- title: Marketing personalizzato
  text: Un piano di comunicazione efficace e personalizzata
  icon: assets/img/100-5.png

- title: Strumenti di vendita
  text: Le dinamiche di vendita sono sempre più complesse e necessitano di strumenti nuovi
  icon: assets/img/100-6.png

- title: Branding
  text: Sviluppiamo un identità per il tuo business
  icon: assets/img/100-1.png

- title: Branding
  text: Sviluppiamo un identità per il tuo business
  icon: assets/img/100-1.png
