- title: Branding
  text: Sviluppiamo il tuo brand, per riuscire a comunicare con i tuoi clienti nel migliori dei modi.
  icon: /assets/img/services/branding.png
  link: /servizi/branding

- title: Social Media Marketing
  text: Aumenta la tua visibilità e coinvolgi i tuoi clienti tramite campagne sui social network (Facebook, Instagram, Twitter...).
  icon: /assets/img/services/social-media-marketing.png
  link: /servizi/social-media-marketing

- title: Web Design & SEO
  text: Creazione siti web e ottimizzazione sui motori di ricerca per far aumentare la visibilità del tuo business e le tue vendite.
  icon: /assets/img/services/seo.png
  link: /servizi/web-design-seo

- title: Content Marketing
  text: Creiamo contenuto di qualità per la tua azienda per far in modo che siano i tuoi clienti a venirti a cercare.
  icon: /assets/img/services/content-marketing.png
  link: /servizi/content-marketing

- title: Local Marketing
  text: Strategie di marketing e di posizionamento a livello locale per aumentare la tua visibilità e fidelizzare i tuoi clienti.
  icon: /assets/img/services/local-search-strategy.png
  link: /servizi/local-marketing

- title: Pubblicità
  text: Raggiungiamo i tuoi clienti ideali tramite pubblicità mirata online e offline.
  icon: /assets/img/services/sparta.png
  link: /servizi/pubblicita
